### PR TITLE
Fix library import (because of numpy.typing issues)

### PR DESCRIPTION
**Pull request by markotoplak**
Referencing numpy.typing without explicit import does not work on numpy 1.26.4. Importing gsffile thus fails.

This small fix fixes the problem for me.

```
>>> import numpy as np
>>> np.__version__
'1.26.4'
>>> np.typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marko/venv310/lib/python3.10/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typing'. Did you mean: '_typing'?
>>> import numpy.typing
>>> np.typing
<module 'numpy.typing' from '/home/marko/venv310/lib/python3.10/site-packages/numpy/typing/__init__.py'>
```

### CODE REVIEW

**Comment by angelo-peronio** [comment]
Thank you! I should test better...

**Comment by angelo-peronio** [comment]
gsffile v0.4.9 is now on PyPI. Could you check if it works for you?

**Comment by markotoplak** [comment]
I tried the new pypi package. My issue is definitely fixed.

Thanks!
